(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},e=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},f=e(this),g;
if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={M:!0},l={};try{l.__proto__=k;h=l.M;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=g,p=function(a,b){a.prototype=d(b.prototype);a.prototype.constructor=a;if(n)n(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var m=Object.getOwnPropertyDescriptor(b,c);m&&Object.defineProperty(a,c,m)}else a[c]=b[c];a.aa=b.prototype};var q=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};var r=function(){var a=HTMLElement.call(this)||this;a.L=!1;return a};p(r,HTMLElement);r.prototype.initialize=function(){};r.prototype.render=function(){};r.prototype.handlePointerUpdate=function(a,b){this.L=!0;this.P=a;this.R=b};r.prototype.handlePointerOut=function(){this.L=!1};r.prototype.shouldRenderOnHoverWhilePaused=function(){return!1};var t={W:"circle",NONE:"none",X:"side-to-side",Y:"up-and-down",Z:"wander",$:"wrap"};var u="autoplay clear-revealed feathering xradius yradius speed track-mouse".split(" "),v=function(){return r.call(this)||this};p(v,r);v.prototype.connectedCallback=function(){this.o=w(this);this.I=this.hasAttribute("clear-revealed");this.J=Math.min(1,Math.max(0,q(this,"feathering",10)/100));this.m=Math.max(1,q(this,"xradius",40));this.s=Math.max(1,q(this,"yradius",40));this.F=q(this,"speed",20);this.G=this.hasAttribute("track-mouse")};
v.prototype.attributeChangedCallback=function(a){switch(a){case "autoplay":this.o=w(this);break;case "clear-revealed":this.I=this.hasAttribute("clear-revealed");break;case "feathering":this.J=Math.min(1,Math.max(0,q(this,"feathering",10)/100));break;case "xradius":this.m=Math.max(1,q(this,"xradius",40));break;case "yradius":this.s=Math.max(1,q(this,"yradius",40));break;case "speed":this.F=q(this,"speed",20);break;case "track-mouse":this.G=this.hasAttribute("track-mouse")}x(this);y(this)};
v.prototype.getPropertyValue=function(a){switch(a){case "autoplay":return this.o;case "clear-revealed":return this.I;case "feathering":return this.J;case "xradius":return this.m;case "yradius":return this.s;case "speed":return this.F;case "track-mouse":return this.G}};
var x=function(a){a.i=a.m*a.u;a.j=a.s*a.u;var b=Math.sqrt(a.h*a.g);"wander"===a.o?a.v=1E-4*a.F*b:"wrap"===a.o&&(a.v=2E-5*a.F*b);b=.06*b+9*a.v;a.O=Math.min(a.h/2,a.i+b);a.T=Math.max(a.h/2,a.h-a.i-b);a.V=Math.min(a.g/2,a.j+b);a.N=Math.max(a.g/2,a.g-a.j-b)},w=function(a){a=a.hasAttribute("autoplay")?a.getAttribute("autoplay"):"wander";return-1!==Object.keys(t).map(function(b){return t[b]}).indexOf(a)?a:"wander"};
v.prototype.initialize=function(a,b,c){b=this.parentElement.querySelector("canvas");this.l=b.getContext("2d");this.h=b.width;this.g=b.height;this.u=c;this.U=a[0]||z(this);this.S=a[1]||z(this);this.A=Math.atan2(this.g,this.h)+.3;this.B=0;this.c=.2*Math.cos(this.A);this.f=.2*Math.sin(this.A);x(this);y(this);"none"===this.o?(this.a=-this.i,this.b=-this.j):(this.a=this.h/2,this.b=this.g/2)};
var y=function(a){if(void 0!==a.l){a.K=A(a);a.H=A(a);a.C=a.H.getContext("2d");var b=a.K.getContext("2d");b.save();b.scale(a.u,a.u);b.translate(a.m,a.s);b.scale(1,a.s/a.m);var c=b.createRadialGradient(0,0,0,0,0,a.m);c.addColorStop(1-a.J,"rgba(0,0,0,1)");c.addColorStop(1,"rgba(0,0,0,0)");b.arc(0,0,a.m,0,2*Math.PI,!1);b.fillStyle=c;b.fill();b.restore()}},z=function(a){var b=a.ownerDocument.createElement("canvas");b.width=a.h;b.height=a.g;return b},A=function(a){var b=a.ownerDocument.createElement("canvas");
b.width=a.m*a.u*2;b.height=a.s*a.u*2;return b};
v.prototype.render=function(a){if(this.L&&this.G)this.a=this.h*this.P,this.b=this.g*this.R;else switch(this.o){case "circle":var b=this.F*a*5E-5;var c=(this.h/2-this.i)/2*Math.cos(b)+this.h/2;b=(this.g/2-this.j)/2*Math.sin(b)+this.g/2;this.G?(this.a=c*(1-.9)+.9*this.a,this.b=b*(1-.9)+.9*this.b):(this.a=c,this.b=b);break;case "wander":if(void 0===this.D)break;c=a-this.D;c=Math.min(50,c);b=Math.sqrt(c);this.c+=.003*(Math.random()-.5)*b;this.f+=.003*(Math.random()-.5)*b;b=!1;this.a<this.O&&.15>this.c&&
(this.c+=8E-4*c,b=!0);this.a>this.T&&-.15<this.c&&(this.c-=8E-4*c,b=!0);this.b<this.V&&.15>this.f&&(this.f+=8E-4*c,b=!0);this.b>this.N&&-.15<this.f&&(this.f-=8E-4*c,b=!0);!1===b&&.15>Math.sqrt(this.c*this.c+this.f*this.f)&&(this.c*=1.05,this.f*=1.05);if(this.a<this.i||this.a>this.h-this.i)this.c*=.9;if(this.b<this.j||this.b>this.g-this.j)this.f*=.9;this.a+=this.c*c*this.v;this.b+=this.f*c*this.v;break;case "wrap":void 0!==this.D&&(c=a-this.D,c=Math.min(50,c),b=Math.sqrt(c),this.B+=.009*(Math.random()-
.5)*b,this.B*=Math.pow(.997,c),this.A+=this.B,b=Math.sin(this.A)*this.v,this.a+=Math.cos(this.A)*this.v*c,this.b+=b*c,this.a>this.h+this.i?this.a-=this.h+2*this.i:this.a<-this.i&&(this.a+=this.h+2*this.i),this.b>this.g+this.j?this.b-=this.g+2*this.j:this.b<-this.j&&(this.b+=this.g+2*this.j))}this.I&&void 0!==this.D||(this.l.clearRect(0,0,this.h,this.g),this.l.globalCompositeOperation="source-over",this.l.drawImage(this.U,0,0));this.C.clearRect(0,0,this.H.width,this.H.height);this.C.globalCompositeOperation=
"source-over";this.C.drawImage(this.K,0,0);this.C.globalCompositeOperation="source-in";this.C.drawImage(this.S,this.i-this.a,this.j-this.b);this.l.globalCompositeOperation="destination-out";this.l.drawImage(this.K,this.a-this.i,this.b-this.j);this.l.globalCompositeOperation="lighter";this.l.drawImage(this.H,this.a-this.i,this.b-this.j);this.D=a};v.prototype.shouldRenderOnHoverWhilePaused=function(){return this.G};f.Object.defineProperties(v,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return u}}});
customElements.define("gwd-reveal",v);}).call(this);
