(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},e=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},f=e(this),g;
if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={U:!0},l={};try{l.__proto__=k;h=l.U;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var m=g,n=function(a,b){a.prototype=d(b.prototype);a.prototype.constructor=a;if(m)m(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var p=Object.getOwnPropertyDescriptor(b,c);p&&Object.defineProperty(a,c,p)}else a[c]=b[c];a.Y=b.prototype};var q=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};var r=function(){var a=HTMLElement.call(this)||this;a.h=!1;return a};n(r,HTMLElement);r.prototype.initialize=function(){};r.prototype.render=function(){};r.prototype.handlePointerUpdate=function(a,b){this.h=!0;this.K=a;this.L=b};r.prototype.handlePointerOut=function(){this.h=!1};r.prototype.shouldRenderOnHoverWhilePaused=function(){return!1};var t="angle autoplay delay feathering hold position speed track-mouse".split(" "),u=function(){var a=r.call(this)||this;a.T=0;return a};n(u,r);
u.prototype.connectedCallback=function(){var a=q(this,"angle",90);this.m=Math.max(0,Math.min(Math.PI,a*Math.PI/180));this.F=this.hasAttribute("autoplay");this.v=1E3*Math.max(0,q(this,"delay",0));this.H=Math.max(0,q(this,"feathering",20));this.b=1E3*Math.max(0,q(this,"hold",0));this.M=Math.max(0,Math.min(100,q(this,"position",50)));this.N=q(this,"speed",20);this.j=this.hasAttribute("track-mouse");v(this)};
u.prototype.attributeChangedCallback=function(a){switch(a){case "angle":a=q(this,"angle",90);this.m=Math.max(0,Math.min(Math.PI,a*Math.PI/180));break;case "autoplay":this.F=this.hasAttribute("autoplay");break;case "delay":this.v=1E3*Math.max(0,q(this,"delay",0));break;case "feathering":this.H=Math.max(0,q(this,"feathering",20));break;case "hold":this.b=1E3*Math.max(0,q(this,"hold",0));break;case "position":this.M=Math.max(0,Math.min(100,q(this,"position",50)));break;case "speed":this.N=q(this,"speed",
20);break;case "track-mouse":this.j=this.hasAttribute("track-mouse")}v(this)};u.prototype.initialize=function(a,b,c){b=this.parentElement.querySelector("canvas");this.u=b.getContext("2d");this.c=b.width;this.a=b.height;this.X=c;this.W=a[0]||w(this);this.V=a[1]||w(this);this.G=w(this);this.O=w(this);this.f=this.G.getContext("2d");this.l=this.O.getContext("2d");v(this)};
u.prototype.getPropertyValue=function(a){switch(a){case "angle":return this.m;case "autoplay":return this.F;case "delay":return this.v;case "feathering":return this.H;case "hold":return this.b;case "position":return this.M;case "speed":return this.N;case "track-mouse":return this.j}};
var v=function(a){a.D=Math.sin(a.m);a.s=Math.cos(a.m);a.g=1.5E-4*a.N;a.C=Math.asin(2*a.M/100-1)/a.g;a.m<Math.PI/2?(a.o=a.D*a.c+a.s*a.a,a.A=0):(a.o=a.D*a.c-a.s*a.a,a.A=a.a);a.S=a.H*a.X/2/a.o;a.P=a.D*a.o;a.R=a.s*a.o;a.B=Math.PI/a.g+a.b;a.i=Math.PI/2/a.g-a.C;a.j||(a.h=!1)},w=function(a){var b=a.ownerDocument.createElement("canvas");b.width=a.c;b.height=a.a;return b};
u.prototype.render=function(a){if(this.h)var b=x(this);else if(-1===a)b=(Math.sin(this.C*this.g)+1)/2;else{if(!1===this.F&&void 0!==this.J)return;if(void 0===this.K&&void 0===this.L&&void 0!==this.J){if(a<this.v)return;a-=this.v}a+=this.T;0===this.b||a<this.i||(a=(a-this.i)%(2*this.B),a=a<this.b?this.i:a<this.B?this.i+a-this.b:a<this.B+this.b?this.i+this.B-this.b:this.i+a-2*this.b);b=Math.sin((a+this.C)*this.g);b=(b+1)/2}var c=b-this.S;b+=this.S;this.I=this.f.createLinearGradient(c*this.P,this.A+
c*this.R,b*this.P,this.A+b*this.R);this.I.addColorStop(0,"rgba(0,0,0,1)");this.I.addColorStop(1,"rgba(0,0,0,0)");this.f.clearRect(0,0,this.c,this.a);this.f.fillStyle=this.I;this.f.globalCompositeOperation="source-over";this.f.fillRect(0,0,this.c,this.a);this.l.clearRect(0,0,this.c,this.a);this.l.globalCompositeOperation="source-over";this.l.drawImage(this.G,0,0);this.l.globalCompositeOperation="source-out";this.l.drawImage(this.V,0,0);this.f.globalCompositeOperation="source-in";this.f.drawImage(this.W,
0,0);this.u.clearRect(0,0,this.c,this.a);this.u.globalCompositeOperation="lighter";this.u.drawImage(this.G,0,0);this.u.drawImage(this.O,0,0);this.J=a};var x=function(a){return(a.D*a.K*a.c+a.s*(a.L*a.a-a.A))/a.o};u.prototype.handlePointerUpdate=function(a,b){this.j&&(this.h=!0,this.K=a,this.L=b)};u.prototype.handlePointerOut=function(){this.j&&(this.h=!1,this.T=Math.asin(2*x(this)-1)/this.g-this.C-this.J)};u.prototype.shouldRenderOnHoverWhilePaused=function(){return this.j};
f.Object.defineProperties(u,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return t}}});customElements.define("gwd-before-and-after",u);}).call(this);
