(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var l;a:{var da={ga:!0},m={};try{m.__proto__=da;l=m.ga;break a}catch(a){}l=!1}h=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=h,p=this||self,r=function(a,b){function c(){}c.prototype=b.prototype;a.Qa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Sa=function(d,e,k){for(var g=Array(arguments.length-2),q=2;q<arguments.length;q++)g[q-2]=arguments[q];return b.prototype[e].apply(d,g)}};var t=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},u=function(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};var v=function(a,b){this.Pa=a;this.ka=b};v.prototype.fetch=function(){navigator.geolocation.getCurrentPosition(this.Ia.bind(this),this.ya.bind(this))};v.prototype.Ia=function(a){a=a.coords;this.Pa(a.latitude,a.longitude,a.accuracy)};v.prototype.ya=function(a){this.ka(a.message)};var w=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},ea=function(a,b){var c=function(d){a.removeEventListener("load",c);b(d)};a.addEventListener("load",c)};var x=function(){this.Oa="https://www.google.com/jsapi";for(var a=["google","load"],b=window,c=0;b&&c<a.length;c++)b=b[a[c]];this.v=b?0:2;this.A=[]};x.prototype.Fa=function(){for(var a=this.v=0;a<this.A.length;a++)this.A[a]();this.A=[]};
x.prototype.load=function(a){a&&(0==this.v?a():this.A.push(a));if(2==this.v){this.v=1;a=document.createElement("script");ea(a,this.Fa.bind(this));a.setAttribute("type","text/javascript");a.setAttribute("async",!0);a.setAttribute("src",this.Oa);var b=document.getElementsByTagName("script")[0];b?b.parentNode.insertBefore(a,b):document.getElementsByTagName("head")[0].appendChild(a)}};var y=null,fa=function(a){y||(y=new x);y.load(function(){google.load("maps","3.28",a)})};var z=function(a,b){this.Ka=a;this.Ja=new google.maps.places.PlacesService(b)};z.prototype.search=function(a,b,c){a={location:a.getCenter()||void 0,radius:3*a.getRadius(),query:this.Ka};this.Ja.textSearch(a,function(d,e){c(e==google.maps.places.PlacesServiceStatus.OK?d:[])})};function A(a){if(Error.captureStackTrace)Error.captureStackTrace(this,A);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}r(A,Error);A.prototype.name="CustomError";var B=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");A.call(this,c+a[d])};r(B,A);B.prototype.name="AssertionError";var ha=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new B(""+d,e||[]);}return a},C=function(a,b){throw new B("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var F=function(a,b){this.T=a===D&&b||"";this.fa=E};F.prototype.$=!0;F.prototype.Y=function(){return this.T};F.prototype.toString=function(){return"Const{"+this.T+"}"};var E={},D={};var H=function(a,b){this.P=b===G?a:""};H.prototype.$=!0;H.prototype.Y=function(){return this.P.toString()};H.prototype.toString=function(){return"SafeUrl{"+this.P+"}"};
var I=function(a){if(a instanceof H&&a.constructor===H)return a.P;var b=typeof a;C("expected object of type SafeUrl, got '"+a+"' of type "+("object"!=b?b:a?Array.isArray(a)?"array":b:"null"));return"type_error:SafeUrl"},ia=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,J=function(a){if(a instanceof H)return a;a="object"==typeof a&&a.$?a.Y():String(a);ha(ia.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez");return new H(a,G)},G={};var K=function(a,b){a:{try{var c=a&&a.ownerDocument,d=c&&(c.defaultView||c.parentWindow);d=d||p;if(d.Element&&d.Location){var e=d;break a}}catch(g){}e=null}if(e&&"undefined"!=typeof e.HTMLAnchorElement&&(!a||!(a instanceof e.HTMLAnchorElement)&&(a instanceof e.Location||a instanceof e.Element))){e=typeof a;if("object"==e&&null!=a||"function"==e)try{var k=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(g){k="<object could not be stringified>"}else k=void 0===
a?"undefined":null===a?"null":typeof a;C("Argument is not a %s (or a non-Element, non-Location mock); got: %s","HTMLAnchorElement",k)}b=b instanceof H?b:J(b);a.href=I(b)},L=function(a){a=a instanceof H?a:J(a);p.open(I(a),"")};var M=function(a){a=a.trim();return window.Enabler?window.Enabler.getUrl(a):a};var N=function(a,b,c,d,e,k,g){this.L=a;this.a=null;this.La=c;this.sa=d;this.ta=e;this.Ma=k;this.c=g;this.ra=g.limit;this.R=g.radius;this.W=null;this.m=0;this.g=this.s=this.Z=this.J=this.K=this.H=this.ca=this.V=this.N=null;this.h=[];this.C=[];this.ea=null;this.b=b.ownerDocument.createElement("div");this.b.className="map";b.appendChild(this.b)},O=function(a,b,c){var d=a.b.ownerDocument.createElement("img"),e=function(){d.removeEventListener("load",e,!1);d.removeEventListener("error",e,!1);d.removeEventListener("abort",
e,!1);c()};d.addEventListener("load",e,!1);d.addEventListener("error",e,!1);d.addEventListener("abort",e,!1);d.setAttribute("src",M(b))};
N.prototype.ja=function(){this.m--;if(0==this.m){var a=this.c;if(a.lat&&a.lng){var b=new google.maps.LatLng(a.lat,a.lng);var c=a.zoom;var d=!0}else b=new google.maps.LatLng(0,0),c=1;c=new google.maps.Map(this.b,{center:b,zoom:c,mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:!1});this.ea=c.getBounds();google.maps.event.addListener(c,"dragend",this.xa.bind(this));google.maps.event.addListener(c,"click",this.Ga.bind(this));var e=M(this.c.markerSource);this.N={url:e,size:new google.maps.Size(34,
34),origin:new google.maps.Point(0,0)};this.V={url:e,size:new google.maps.Size(34,34),origin:new google.maps.Point(34,0)};this.ca={url:e,size:new google.maps.Size(37,34),origin:new google.maps.Point(68,0),anchor:new google.maps.Point(10,34)};this.K={url:M(this.c.gpsIconSource),size:new google.maps.Size(32,32),anchor:new google.maps.Point(0,0)};this.W=new z(a.query||"*",c);d&&new google.maps.Marker({position:b,map:c,icon:this.K});this.a=c;this.La()}};
N.prototype.xa=function(){if(this.s){for(var a=this.a.getBounds(),b=!0,c=0;c<this.C.length;c++)if(a.contains(this.C[c].geometry.location||null)){b=!1;break}b&&!this.s.getBounds().contains(this.a.getCenter())&&(this.u(),this.Ma())}};N.prototype.u=function(){this.g&&(this.g.setIcon(this.N),this.g=null)};
var P=function(a,b,c,d){a.a&&(b=new google.maps.LatLng(b,c),c=a.a,a.J=b,c.setCenter(b),new google.maps.Marker({position:b,map:c,icon:a.K}),d&&(a.R=d,a.Z=new google.maps.Circle({center:b,radius:a.R,map:c,fillColor:"#a2d1f5",fillOpacity:.5,strokeWeight:0}),c.fitBounds(a.Z.getBounds())))};f=N.prototype;f.search=function(a){if(this.a){var b=this.R,c=10-this.a.getZoom();0<c&&(b*=c);this.s=new google.maps.Circle({center:this.a.getCenter(),radius:b});this.W.search(this.s,this.ra,this.B.bind(this,a))}};
f.B=function(a,b){for(var c=0;c<this.h.length;c++)this.h[c].setMap(null),google.maps.event.clearInstanceListeners(this.h[c]);this.h.length=0;this.C=b;for(c=0;c<b.length;c++){var d=new google.maps.Marker({position:b[c].geometry.location,map:this.a,icon:this.N,Ta:this.ca});google.maps.event.addListener(d,"click",this.O.bind(this,c));this.h.push(d)}this.a.fitBounds(this.s.getBounds());if(c=0<b.length)d=this.a.getBounds(),b=b[0].geometry.location||null,d&&!d.contains(b)&&(d.extend(b),this.a.fitBounds(d));
a(c)};f.Ga=function(){this.u();this.sa()};f.O=function(a){this.u();this.g=this.h[a];this.ta(this.C[a],this.la.bind(this))};f.la=function(a){this.g.setIcon(this.V);this.a.panTo(this.g.getPosition());this.a.panBy(0,a)};f.pa=function(a,b,c,d){d==google.maps.GeocoderStatus.OK?(b=c[0].geometry.location,this.a.setCenter(b),this.a.fitBounds(c[0].geometry.viewport),P(this,b.lat(),b.lng()),a()):b()};var R=function(a,b,c,d){this.L=a;this.G=null;this.ia=c;this.oa=d;this.b=b.ownerDocument.createElement("div");this.b.className="ip";a=b.ownerDocument.createElement("div");a.className="bg";this.b.appendChild(a);c=b.ownerDocument.createElement("a");c.className="dir";c.appendChild(b.ownerDocument.createElement("div"));a.appendChild(c);c.addEventListener("click",this.Ea.bind(this),!1);c=b.ownerDocument.createElement("div");c.className="res";this.U=b.ownerDocument.createElement("div");this.U.className=
"title";this.F=b.ownerDocument.createElement("div");this.F.className="address";this.o=b.ownerDocument.createElement("div");this.o.className="tel";d=this.i=b.ownerDocument.createElement("a");var e=new F(D,"#");e instanceof F&&e.constructor===F&&e.fa===E?e=e.T:(C("expected object of type Const, got '"+e+"'"),e="type_error:Const");K(d,new H(e,G));this.o.appendChild(this.i);c.appendChild(this.U);c.appendChild(this.F);c.appendChild(this.o);a.appendChild(c);this.i.addEventListener("click",this.ua.bind(this));
c=b.ownerDocument.createElement("a");c.className="close";c.appendChild(b.ownerDocument.createElement("div"));a.appendChild(c);c.addEventListener("click",this.va.bind(this),!1);Q(this);b.appendChild(this.b)},Q=function(a){a.b.classList.add("hidden")};R.prototype.ua=function(a){a.preventDefault();a=this.i.href;w("calllocation",this.L,{url:a}).detail.handled||L(a)};R.prototype.va=function(a){a.preventDefault();Q(this);this.ia()};R.prototype.Ea=function(a){a.preventDefault();this.G&&this.oa(this.G)};var S=function(a){var b=document.createElement("div");b.className="bg hidden";var c=document.createElement("div");c.className="loading";c.appendChild(document.createElement("div"));b.appendChild(c);this.b=b;a.appendChild(this.b)};S.prototype.show=function(){this.b.classList.remove("hidden")};var T=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},U=function(a){if(T(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&T(a))return a;return null};var V=function(a,b,c,d){this.I=b;this.na=c;this.b=ja(this,d);this.ma=this.b.querySelector("form");this.qa=this.b.querySelector("input");this.Ra=this.b.querySelector(".title");this.ha=this.b.querySelector(".btns");a.appendChild(this.b)},ja=function(a,b){var c=document.createElement("div"),d=document.createElement("div");d.classList.add("diag");c.appendChild(d);var e=document.createElement("div");e.classList.add("title");e.textContent=b.title;d.appendChild(e);e=document.createElement("div");e.classList.add("btns");
d.appendChild(e);var k=document.createElement("form");k.setAttribute("method","get");d.appendChild(k);var g=document.createElement("input");g.placeholder=b.geocodePlaceholder;g.type="search";k.appendChild(g);a.I?(W(e,b.gpsLabel,a.I),W(e,b.geocodeLabel,a.S.bind(a,b.geocodeTitle))):e.classList.add("hidden");b=c.querySelector("form");b.addEventListener("submit",function(q){q.preventDefault();this.na(g.value)}.bind(a),!1);a.I&&b.classList.add("hidden");c.classList.add("bg");return c},W=function(a,b,c){var d=
document.createElement("a");d.textContent=b;d.addEventListener("click",function(e){e.preventDefault();c()},!1);d.setAttribute("href","#");a.appendChild(d)};V.prototype.S=function(a){this.Ra.textContent=a;this.ha.classList.add("hidden");this.ma.classList.remove("hidden");this.b.classList.remove("hidden");this.qa.focus()};var ka=["start-latitude","start-longitude","query"],X=function(){var a=HTMLElement.call(this)||this;a.ba=!1;a.M=!1;a.aa=!1;return a},Y=HTMLElement;X.prototype=aa(Y.prototype);X.prototype.constructor=X;if(n)n(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var la=Object.getOwnPropertyDescriptor(Y,Z);la&&Object.defineProperty(X,Z,la)}else X[Z]=Y[Z];X.Qa=Y.prototype;f=X.prototype;
f.connectedCallback=function(){if(!this.a){for(;this.firstChild;)this.removeChild(this.firstChild);var a={geocodeFailure:u(this,"msg-geocode-failure","Your location could not be determined. Please enter a valid address."),gpsIconSource:u(this,"gps-src","assets/location.png"),limit:t(this,"result-limit",20),locationDialogConfig:{title:u(this,"msg-start-position-prompt","How would you like us to get your position?"),gpsLabel:u(this,"msg-gps-button-label","Use GPS"),geocodeLabel:u(this,"msg-manual-position-button-label",
"Enter address or zip code"),geocodeTitle:u(this,"msg-manual-position-prompt","Enter address or zip code"),geocodePlaceholder:u(this,"msg-manual-position-placeholder","Address or zip code")},markerSource:u(this,"marker-src","assets/marker_sprite.png"),noResultsError:u(this,"msg-no-results-found","No results found near you."),radius:t(this,"search-radius",4E4),requestLocation:this.hasAttribute("request-user-location")||!this.hasAttribute("start-latitude")||!this.hasAttribute("start-longitude"),zoom:t(this,
"start-zoom",16),showLocationBar:this.hasAttribute("show-location-bar"),includeDirections:this.hasAttribute("include-directions"),includeClickToCall:this.hasAttribute("include-click-to-call"),includeDrapeImage:this.hasAttribute("include-drape-image")};this.hasAttribute("query")&&(a.query=this.getAttribute("query"));this.hasAttribute("start-latitude")&&(a.lat=parseFloat(this.getAttribute("start-latitude")));this.hasAttribute("start-longitude")&&(a.lng=parseFloat(this.getAttribute("start-longitude")));
this.hasAttribute("client-id")&&(a.clientId=this.getAttribute("client-id"));this.hasAttribute("api-key")&&(a.apiKey=this.getAttribute("api-key"));a.showLocationBar&&this.hasAttribute("location-bar-color")&&(a.locationBarColor=this.getAttribute("location-bar-color"));a.includeDrapeImage&&this.hasAttribute("drape-image-source")&&(a.drapeImageSource=this.getAttribute("drape-image-source"));this.c=a;var b=this.ownerDocument.createElement("div");b.className="sizer";this.a=new N(this,b,this.Ha.bind(this),
this.da.bind(this),this.O.bind(this),this.D.bind(this),a);this.X=navigator.geolocation?new v(this.Da.bind(this),this.Ba.bind(this)):null;this.l=new V(b,this.X&&this.Ca.bind(this),this.Aa.bind(this),a.locationDialogConfig);a.requestLocation||Q(this.l);this.f=new S(b);this.appendChild(b);this.Na=b}this.gwdIsLoaded()||((a=U(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.gwdIsActive()||((a=U(this))?a.gwdIsActive()&&this.gwdActivate():this.gwdActivate());a=this.a;a.a&&google.maps.event.trigger(a.a,
"resize")};f.attributeChangedCallback=function(a,b,c){if(this.a)switch(a){case "query":this.a.c.query=c||"";break;case "start-latitude":this.a.c.lat=parseFloat(c);break;case "start-longitude":this.a.c.lng=parseFloat(c)}};
f.gwdLoad=function(){if(!this.aa){this.aa=!0;var a=this.a,b=a.ja.bind(a);a.m=2;O(a,a.c.markerSource,b);a.m++;O(a,a.c.gpsIconSource,b);a.m++;var c=a.c.clientId;a=a.c.apiKey;var d="";a&&!c&&(d="&key="+a);fa({callback:b,other_params:"sensor=true&libraries=places"+(c?"&client="+c:"")+d});b()}};f.gwdIsLoaded=function(){return this.ba};f.gwdActivate=function(){this.classList.remove("deactivated");this.M=!0};f.gwdDeactivate=function(){this.classList.add("deactivated");this.M=!1};f.gwdIsActive=function(){return this.M};
f.setCenter=function(a,b,c){Q(this.f);P(this.a,a,b,c);this.D()};f.Ha=function(){this.c.requestLocation||this.D();this.classList.add("ready");this.ba=!0;w("ready",this)};f.Ca=function(){this.f.show();Q(this.l);this.X.fetch()};f.Da=function(a,b,c){this.setCenter(a,b,c)};f.Ba=function(a){Q(this.f);this.l.S(a)};f.Aa=function(a){this.f.show();Q(this.l);var b=this.a,c=this.D.bind(this),d=this.za.bind(this);b.a&&(b.H||(b.H=new google.maps.Geocoder),b.H.geocode({address:a,bounds:b.ea},b.pa.bind(b,c,d)))};
f.D=function(){this.c.query?(this.f.show(),this.a.search(this.B.bind(this))):Q(this.f);this.da();w("mapopen",this)};f.B=function(a){Q(this.f);a?w("resultsfound",this):(this.l.S(this.c.geocodeFailure),w("resultsnotfound",this))};f.za=function(){this.B(!1)};f.da=function(){this.j&&Q(this.j)};
f.O=function(a,b){this.j||(this.j=new R(this,this.Na,this.a.u.bind(this.a),this.wa.bind(this)));var c=this.j;c.G=a;c.U.textContent=a.name;var d=a.vicinity||a.formatted_address;d=d.replace(/, /,",\n");c.F.textContent=d;if(a.formatted_phone_number){c.o.classList.remove("hidden");c.i.textContent=a.formatted_phone_number;d="tel:"+a.formatted_phone_number.replace(/[^\d]/g,"");var e=String(d.substr(0,4)).toLowerCase();0==("tel:"<e?-1:"tel:"==e?0:1)||(d="about:invalid#zClosurez");K(c.i,new H(d,G))}else c.o.classList.add("hidden");
c.b.classList.remove("hidden");b(this.j.b.firstChild.offsetHeight/2);b=a.geometry.location.lat();a=a.geometry.location.lng();w("pinclick",this,{lat:b,lng:a})};f.wa=function(a){var b=this.a;if(b.a){var c=b.J?b.J.toString():"";a=encodeURIComponent(a.formatted_address);c="https://maps.google.com/maps?saddr="+escape(c)+"&daddr="+a;w("getdirections",b.L,{url:c}).detail.handled||L(c)}};ca.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ka}}});
customElements.define("gwd-map",X);}).call(this);
