(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");},ca=ba(this),k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var q;a:{var da={Qa:!0},u={};try{u.__proto__=da;q=u.Qa;break a}catch(a){}q=!1}k=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var v=k;var ea={o:0,s:0,u:0,v:0,A:"#fff",B:"#fff",C:0,l:0,g:0,D:"0px",F:"0px",G:"0px",H:"0px",loop:!1,I:0,J:1,K:1,L:0,N:!1,shape:"square",P:1,R:1,S:0,T:0,i:0,j:0,aa:"",O:!1,m:1,U:0,f:1,V:1},fa={o:0,s:0,u:280,v:260,A:"#fff",B:"#fff",C:0,l:.005,g:2,D:"100%",F:"0%",G:"10%",H:"0%",loop:!0,I:0,J:1,K:.1,L:0,N:!0,shape:"circle",P:12,R:8,S:0,T:0,i:2,j:1,aa:"",O:!1,m:1,U:0,f:1,V:1},ha={o:0,s:.6,u:271,v:269,A:"#fff",B:"#fff",C:0,l:.01,g:2,D:"100%",F:"0%",G:"10%",H:"0%",loop:!0,I:0,J:1,K:.5,L:0,N:!0,shape:"line",P:25,
R:10,S:0,T:100,i:10,j:8,aa:"",O:!1,m:1,U:0,f:1,V:1},ia={o:0,s:.6,u:100,v:80,A:"#ffdc00",B:"#dc000a",C:1.2,l:0,g:1,D:"20px",F:"10px",G:"40px",H:"35px",loop:!0,I:10,J:.3,K:.1,L:-.3,N:!1,shape:"teardrop",P:20,R:20,S:-30,T:100,i:1,j:.5,aa:"",O:!0,m:20,U:.18,f:1,V:30},ja={o:0,s:.6,u:100,v:80,A:"#ffdc00",B:"#dc000a",C:1,l:0,g:2,D:"50px",F:"20px",G:"100px",H:"95px",loop:!0,I:15,J:.3,K:.1,L:-.3,N:!1,shape:"teardrop",P:40,R:40,S:-30,T:100,i:2,j:1,aa:"",O:!0,m:20,U:.18,f:1,V:30},ka={o:0,s:.6,u:100,v:80,A:"#ffdc00",
B:"#dc000a",C:.8,l:0,g:4,D:"80px",F:"30px",G:"180px",H:"175px",loop:!0,I:15,J:.3,K:.1,L:-.3,N:!1,shape:"teardrop",P:100,R:100,S:-54,T:100,i:3,j:2,aa:"",O:!0,m:20,U:.18,f:1,V:25},la={o:0,s:0,u:90,v:90,A:"#dcdcdc",B:"#dcdcdc",C:0,l:0,g:25,D:"22px",F:"10px",G:"120px",H:"100px",loop:!0,I:8,J:.03,K:.03,L:-.018,N:!0,shape:"teardrop",P:15,R:15,S:-.06,T:100,i:1,j:.8,aa:"",O:!0,m:60,U:.6,f:.5,V:40},ma={o:0,s:.06,u:100,v:80,A:"#dcdcdc",B:"#dcdcdc",C:0,l:0,g:2,D:"35px",F:"10px",G:"150px",H:"148px",loop:!0,I:300,
J:.1,K:.1,L:-.03,N:!0,shape:"circle",P:20,R:10,S:-1.2,T:100,i:.8,j:.8,aa:"",O:!0,m:10,U:0,f:.5,V:1};var w=function(a,b,d){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=d);return a},A=function(a,b,d){a=w(a,b,d);return 0<a?a:d},B=function(a,b,d){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=d);return a},C=function(a,b,d){return a.hasAttribute(b)?a.getAttribute(b):d},D=function(a,b,d){switch(a.getAttribute(b)){case "true":return!0;case "false":return!1;default:return d}};var na=/[^\d]+$/,G=function(a,b,d,c){if(!a.hasAttribute(b))return d;a=a.getAttribute(b);return isNaN(parseFloat(a))?d:E(a,c)},E=function(a,b){var d=parseFloat(a);(a=(a=a.match(na))&&a[0]||null)&&(a=a.trim());var c=d;"%"==a&&(c=Number((d/100*b).toFixed(2)));return c};var oa=/^#(?:[0-9a-f]{3}){1,2}$/i,pa=/#(.)(.)(.)/,H=[60,6E3],I=function(a){if(!oa.test(a))return null;4==a.length&&(a=a.replace(pa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},J=function(a,b,d,c,e){b=B(a,b,c);a=B(a,d,e);b>a&&(d=b,b=a,a=d);return[b,a]},qa=function(a){switch(a){case "snow":return fa;case "rain":return ha;case "fire-small":return ia;case "fire-medium":return ja;case "fire-large":return ka;case "steam":return la;case "smoke":return ma;default:return ea}},
K=function(a,b,d,c,e,f){b=G(a,b,c,f);a=G(a,d,e,f);b>a&&(d=b,b=a,a=d);return[b,a]};var L=function(a,b,d){return a+d*(b-a)},M=function(a){return a*a*a*(a*(6*a-15)+10)},P=function(a,b,d,c){switch(a%16){case 0:return b+d;case 1:return-b+d;case 2:return b-d;case 3:return-b-d;case 4:return b+c;case 5:return-b+c;case 6:return b-c;case 7:return-b-c;case 8:return d+c;case 9:return-d+c;case 10:return d-c;case 11:return-d-c;case 12:return b+d;case 13:return-d+c;case 14:return-b+d;case 15:return-d-c;default:return 0}},ra=function(){for(var a=Array(256),b=0;b<a.length;++b)a[b]=b;for(b=a.length-
1;0<b;--b){var d=Math.floor(Math.random()*a.length),c=a[b];a[b]=a[d];a[d]=c}this.Wa=a.concat(a)},Q=function(a,b,d,c){var e=b&255,f=d&255,g=c&255;b-=Math.floor(b);d-=Math.floor(d);c-=Math.floor(c);var l=M(b),h=M(d);a=a.Wa;return L(L(L(P(a[a[a[e]+f]+g],b,d,c),P(a[a[a[e+1]+f]+g],b-1,d,c),l),L(P(a[a[a[e]+f+1]+g],b,d-1,c),P(a[a[a[e+1]+f+1]+g],b-1,d-1,c),l),h),L(L(P(a[a[a[e]+f]+g+1],b,d,c-1),P(a[a[a[e+1]+f]+g+1],b-1,d,c-1),l),L(P(a[a[a[e]+f+1]+g+1],b,d-1,c-1),P(a[a[a[e+1]+f+1]+g+1],b-1,d-1,c-1),l),h),M(c))};var R=function(a){this.Ia=a;this.Fa=[];this.length=this.la=0};R.prototype.get=function(a){return this.Fa[(a+this.la)%this.length]};R.prototype.push=function(a){this.length<this.Ia&&this.length++;this.Fa[this.la]=a;this.la=(this.la+1)%this.Ia};var sa=2*Math.PI,S=function(a,b){return a+Math.random()*(b-a)},U=function(a,b){this.h=[];this.b=b;this.c=a.getContext("2d");this.xa=window.devicePixelRatio;this.Ca=1;this.Ga=[];this.Ha=[];if("image"!=this.b.pa.shape)a=null;else if((a=this.b.pa.Va)&&0!=a.length){b=[];this.Ca=this.b.oa.max*this.xa;for(var d=0;d<a.length;d++){var c=a[d],e=document.createElement("canvas"),f=e.getContext("2d"),g=this.Ca/Math.max(c.naturalWidth,c.naturalHeight),l=c.naturalWidth*g;g*=c.naturalHeight;e.width=Math.ceil(l);
e.height=Math.ceil(g);f.drawImage(c,0,0,l,g);b.push(e);this.Ga.push(-l/2);this.Ha.push(-g/2)}a=b}else this.b.pa.shape="square",a=null;this.ya=a;this.ma=0;this.Ta=0==this.b.g?this.b.Aa:1/this.b.g;a=this.b.ca;this.wa=a.ha?0:(a.ka-a.ta)*a.Ba;this.va=a.ha?0:(a.ja-a.sa)*a.Ba;this.ua=a.ha?0:(a.ia-a.ra)*a.Ba;this.Da=(a=this.b.Ka)?new ra:null;this.Ea=a?a.frequency:1;this.$a=a?a.Ya:1;this.La=a&&a.Za-1||0;for(a=0;a<this.b.Ja;a++)T(this)};U.prototype.reset=function(){for(var a=this.ma=this.h.length=0;a<this.b.Ja;a++)T(this)};
var V=function(a){var b=S(a.b.na.Na,a.b.na.Ma),d=S(a.b.na.Pa,a.b.na.Oa),c=S(a.b.oa.min,a.b.oa.max),e=S(a.b.za.min,a.b.za.max),f=a.b.ca,g=f.ta,l=f.sa,h=f.ra;f.ha&&(h=Math.random(),g=(1-h)*f.ta+h*f.ka,l=(1-h)*f.sa+h*f.ja,h=(1-h)*f.ra+h*f.ia);var n=S(a.b.qa.j,a.b.qa.i);f=S(a.b.qa.Sa,a.b.qa.Ra);var y=n*Math.cos(f);n*=Math.sin(f);var x=-1;a.ya&&(x=Math.floor(S(0,a.ya.length)));return{a:{positionX:b,positionY:d,size:c,Y:g,X:l,W:h,opacity:e,ea:!0,angle:f,fa:x},velocityX:y,velocityY:n,f:a.$a,ba:a.La?new R(a.La):
null}},T=function(a){for(var b=Date.now()/a.Ea,d=0;d<a.h.length;d++){var c=a.h[d],e=a;c.ba&&c.ba.push({positionX:c.a.positionX,positionY:c.a.positionY,size:c.a.size,Y:c.a.Y,X:c.a.X,W:c.a.W,opacity:c.a.opacity,angle:c.a.angle,fa:c.a.fa,ea:c.a.ea});if(c.a.ea){c.a.positionX+=c.velocityX;c.a.positionY+=c.velocityY;if(e.Da&&0<c.f){var f=c.a.positionX/e.Ea,g=c.a.positionY/e.Ea;c.a.positionX+=c.f*Q(e.Da,f,g,b);c.a.positionY+=c.f*Q(e.Da,b,f,g);c.f+=e.b.Ka.rate}c.a.size+=e.b.oa.rate;c.a.opacity=Math.min(1,
c.a.opacity+e.b.za.rate);c.velocityX+=e.b.acceleration.x;c.velocityY+=e.b.acceleration.y;c.a.angle=Math.atan2(c.velocityY,c.velocityX);f=e.b.ca;f.ha||((!e.wa||1<(f.ka-c.a.Y)/e.wa)&&(!e.va||1<(f.ja-c.a.X)/e.va)&&(!e.ua||1<(f.ia-c.a.W)/e.ua)?(c.a.Y+=e.wa,c.a.X+=e.va,c.a.W+=e.ua):(c.a.Y=e.b.ca.ka,c.a.X=e.b.ca.ja,c.a.W=e.b.ca.ia))}if(0>c.a.positionX+c.a.size||c.a.positionX-c.a.size>a.b.width||0>c.a.positionY+c.a.size||c.a.positionY-c.a.size>a.b.height||0>c.a.opacity||0>c.a.size)a.b.Xa?(c=c.ba,a.h[d]=
V(a),a.h[d].ba=c):c.a.ea=!1}if(a.h.length<a.b.Aa)for(a.ma=Math.min(a.ma+a.Ta,a.b.Aa),b=Math.floor(a.ma)-a.h.length,d=0;d<b;d++)a.h.push(V(a))},ta=function(a,b){if(b.ea){a.c.fillStyle="rgba("+Math.round(b.Y)+", "+Math.round(b.X)+", "+Math.round(b.W)+", "+b.opacity+")";a.c.save();a.c.translate(b.positionX,b.positionY);var d=b.size/a.Ca;a.c.scale(d,d);switch(a.b.pa.shape){case "circle":a.c.beginPath();a.c.arc(0,0,.5,0,sa);a.c.fill();break;case "line":a.c.beginPath();a.c.rotate(b.angle);a.c.fillRect(-.5,
-.01,1,.02);break;case "teardrop":a.c.beginPath();a.c.moveTo(.08,-.5);a.c.bezierCurveTo(.13,-.21,.16,.04,.3,.07);a.c.bezierCurveTo(.44,.36,.13,.5,-.06,.5);a.c.bezierCurveTo(-.49,.14,-.41,0,.08,-.5);a.c.fill();break;case "image":a.c.globalAlpha=b.opacity;a.c.drawImage(a.ya[b.fa],a.Ga[b.fa],a.Ha[b.fa]);break;default:a.c.beginPath(),a.c.fillRect(-.5,-.5,1,1)}a.c.restore()}};var ua=function(a,b){var d=void 0===d?null:d;var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,d);b.dispatchEvent(c)};var va=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},wa=function(a){if(va(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&va(a))return a;return null},xa=function(a){return(a=C(a,"sprite-image-src",""))?a.split(",").map(function(b){return b.trim()}):[]};var ya={ab:"acceleration-x",bb:"acceleration-y",cb:"angle-max",eb:"angle-min",fb:"autoplay",gb:"color1",hb:"color2",ib:"color-rate",jb:"custom-preset",kb:"emit-interval",lb:"emit-x-max",mb:"emit-x-min",nb:"emit-y-max",ob:"emit-y-min",pb:"loop",qb:"number",rb:"opacity-max",sb:"opacity-min",tb:"opacity-rate",ub:"preset-type",vb:"random-colors",wb:"shape",xb:"size-max",yb:"size-min",zb:"size-rate",Ab:"skip-forward",Bb:"speed-max",Cb:"speed-min",Db:"sprite-image-src",Eb:"turbulence-frequency",Fb:"turbulence-rate",
Gb:"turbulence-strength",Hb:"turbulence-trail"},za=[],Aa=0,Ba;for(Ba in ya)za[Aa++]=ya[Ba];var W=function(){var a=HTMLElement.call(this)||this;a.M=null;a.$=0;a.Z=[];a.da=a.Ua.bind(a);a.ga=2;return a},X=HTMLElement;W.prototype=aa(X.prototype);W.prototype.constructor=W;if(v)v(W,X);else for(var Y in X)if("prototype"!=Y)if(Object.defineProperties){var Ca=Object.getOwnPropertyDescriptor(X,Y);Ca&&Object.defineProperty(W,Y,Ca)}else W[Y]=X[Y];W.prototype.attributeChangedCallback=function(){this.reset()};
W.prototype.connectedCallback=function(){if(!this.gwdIsLoaded()){var a=wa(this);a?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad()}};W.prototype.disconnectedCallback=function(){Z(this);this.M=null};W.prototype.gwdLoad=function(){if(!this.M){Z(this);var a=xa(this);if(this.$=a.length)for(var b=0;b<this.$;b++){var d=this.ownerDocument.createElement("img");d.addEventListener("load",this.da,!1);d.addEventListener("error",this.da,!1);d.src=a[b];this.Z.push(d)}0===this.$&&Da(this)}};
W.prototype.gwdIsLoaded=function(){return!!this.M};
var Z=function(a){for(;a.Z.length;){var b=a.Z.pop();b.removeEventListener("load",a.da,!1);b.removeEventListener("error",a.da,!1)}a.$=0},Da=function(a){var b=a.getAttribute("preset-type"),d=a.Z.length?a.Z:null;if(a.parentElement){var c=a.parentElement.getElementsByTagName("canvas")[0];if(c){var e=a.parentElement.clientWidth,f=a.parentElement.clientHeight;b=qa(b);var g=E(b.F,e),l=E(b.D,e),h=E(b.H,f),n=E(b.G,f);g=K(a,"emit-x-min","emit-x-max",g,l,e);h=K(a,"emit-y-min","emit-y-max",h,n,f);h={Na:g[0],
Ma:g[1],Pa:h[0],Oa:h[1]};n=b.I;b.l&&(n=Math.ceil(b.l*(h.Ma-h.Na)*(h.Oa-h.Pa)));n=Math.min(A(a,"number",n),1E3);g=A(a,"emit-interval",b.g);l=b.T;var y=w(a,"skip-forward",l);l=Math.round((0<=y?y:l)*Math.min(Math.max(n*g,H[0]),H[1])/100);y=D(a,"loop",b.loop);var x=J(a,"size-min","size-max",b.R,b.P),z=B(a,"size-rate",b.S)/60;x={min:x[0],max:x[1],rate:z};z=J(a,"opacity-min","opacity-max",b.K,b.J);var t=B(a,"opacity-rate",b.L)/60;z={min:z[0],max:z[1],rate:t};t=C(a,"color1",b.A);var r=C(a,"color2",b.B);
t=I(t);r=I(r);var m=D(a,"random-colors",b.N),p=B(a,"color-rate",b.C)/60;t={ha:m,ta:t[0],sa:t[1],ra:t[2],ka:r[0],ja:r[1],ia:r[2],Ba:p};r=J(a,"speed-min","speed-max",b.j,b.i);m=J(a,"angle-min","angle-max",b.v,b.u);m[0]=-m[0];m[1]=-m[1];r={j:r[0],i:r[1],Sa:m[1]/180*Math.PI,Ra:m[0]/180*Math.PI};m=B(a,"acceleration-x",b.o)/60;p=B(a,"acceleration-y",b.s)/60;m={x:m,y:p};p=C(a,"shape",b.shape);d={shape:p,Va:"image"==p?d:null};p=a.hasAttribute("turbulence-frequency");var F=a.hasAttribute("turbulence-strength"),
N=a.hasAttribute("turbulence-rate"),O=a.hasAttribute("turbulence-trail");b.O||p||F||N||O?(p=B(a,"turbulence-frequency",b.m),F=B(a,"turbulence-strength",b.f),N=B(a,"turbulence-rate",b.U)/60,O=Math.min(A(a,"turbulence-trail",b.V),100),b={frequency:0<p?p:b.m,Ya:0<F?F:b.f,rate:N,Za:O}):b=null;a.M=new U(c,{width:e,height:f,Aa:n,g:g,Ja:l,na:h,oa:x,za:z,ca:t,qa:r,acceleration:m,Xa:y,pa:d,Ka:b});ua("ready",a)}}};
W.prototype.Ua=function(a){var b=a.target;b.removeEventListener("load",this.da,!1);b.removeEventListener("error",this.da,!1);b=this.Z.indexOf(b);0<=b&&("error"===a.type&&this.Z.splice(b,1),this.$--);0===this.$&&Da(this)};W.prototype.updateAndDraw=function(){0===this.ga&&T(this.M);if(2!=this.ga){var a=this.M;a.c.save();a.c.scale(a.xa,a.xa);for(var b=0;b<a.h.length;b++){var d=a.h[b];if(d.ba)for(var c=0;c<d.ba.length;c++)ta(a,d.ba.get(c));ta(a,d.a)}a.c.restore()}};
W.prototype.play=function(){this.ga=0};W.prototype.pause=function(){this.ga=1};W.prototype.stop=function(){this.ga=2;this.M.reset()};W.prototype.reset=function(){Z(this);this.M=null;ua("request-reload",this)};ca.Object.defineProperties(W,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return za}}});customElements.define("gwd-particles",W);}).call(this);
