(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var k,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},l=ba(this),m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={ra:!0},q={};try{q.__proto__=ca;n=q.ra;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var v=m,y=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(v)v(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Ja=b.prototype},z=this||self,A=function(a,b){function c(){}c.prototype=b.prototype;a.Ja=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ka=function(d,e,h){for(var g=Array(arguments.length-2),f=2;f<arguments.length;f++)g[f-2]=arguments[f];return b.prototype[e].apply(d,
g)}};var B=function(a,b){return a.x*b.x+a.y*b.y},F=function(a,b){return C(b,B(a,b))},C=function(a,b){return G(a.x*b,a.y*b)},G=function(a,b){return{x:a,y:void 0!==b?b:a}};var H=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},I=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};var J=function(a,b){return window.setTimeout(a,b)};var K=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},da=function(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;J(function(){var d=K("autoplayended",a,b);c&&c(d)},0)},ea=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)},fa=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=J(function(){c=null;b&&(a(),b=!1)},250))}};var M=["-ms-","-moz-","-webkit-",""],N=function(a,b,c){var d=void 0===d?!1:d;for(var e,h,g=0;g<M.length;g++)e=M[g]+b,h=(d?M[g]:"")+c,a.style.setProperty(e,h)};var O=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},ha=function(a){if(O(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&O(a))return a;return null},ia=function(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)},ja=function(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};function P(a){if(Error.captureStackTrace)Error.captureStackTrace(this,P);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}A(P,Error);P.prototype.name="CustomError";var R=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");P.call(this,c+a[d])};A(R,P);R.prototype.name="AssertionError";var ka=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new R(""+d,e||[]);}return a},la=function(a,b){throw new R("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var S=function(a,b){this.T=b===ma?a:""};S.prototype.ua=!0;S.prototype.ta=function(){return this.T.toString()};S.prototype.toString=function(){return"SafeUrl{"+this.T+"}"};var na=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,ma={};var oa=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)if(!/^[\s\xa0]*$/.test(a[c])){var d=b,e=d.push;var h=a[c];h=h.trim();h=window.Enabler?window.Enabler.getUrl(h):h;var g=document.createElement("gwd-image");g.setAttribute("source",h);e.call(d,g)}}return b},pa=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}},qa=function(a,b){return"left"==a||"backwards"==a?-b:b},ra=
function(a,b){return(a%b+b)%b};var sa=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},T=function(a){this.l=a;this.A=null;this.Ia=!0;this.P=!1};
T.prototype.play=function(a,b,c){var d=this;b=void 0===b?"forwards":b;if(this.l.frameCount&&null==this.A){if(c){var e=Math.floor(a/c);a=c}else e=this.l.frameCount,a/=e;var h=[],g=sa(this.l);c=g;for(var f=0;f<e;f++){if(0<f||!this.Ia)c=ra(c+qa(b,1),this.l.frameCount);h.push(c)}b=function(){if(h.length){var t=h.shift();d.P=!0;d.l.goToFrame(t+1);d.P=!1;K("frameautoplayed",d.l,{id:t+1})}else d.stop(!0),d.l.goToFrame(g+1)};this.A=window.setInterval(b,a);setTimeout(b)}};
T.prototype.stop=function(a){a=void 0===a?!1:a;!this.P&&this.A&&(window.clearInterval(this.A),da(this.l,{completed:a}),this.A=null)};var ta=["pause-front-media","resume-next-media"],U=function(){var a=HTMLElement.call(this)||this;a.frames=[];a.a=null;a.c=0;a.j=1;a.C=new T(a);a.ia=!1;a.ka=!1;return a};y(U,HTMLElement);k=U.prototype;k.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.ia="true"==c;break;case "resume-next-media":this.ka="true"==c}};k.gwdIsLoaded=function(){return!0};k.gwdLoad=function(){};
k.goToFrame=function(a,b){this.stopRotation();0!=this.c&&(a>this.c?a=this.c:1>a&&(a=1),this.aa(a,b))};k.aa=function(a){this.a=a-1};var ua=function(a,b,c,d){if(null!=a.a){var e=a.j;e=ra(a.a+qa(b,void 0===e?1:e),a.j*Math.ceil(a.c/a.j));!d&&("forwards"==b&&e<a.a||"backwards"==b&&e>a.a)||a.goToFrame(e+1,c)}};k=U.prototype;k.goBackwards=function(a,b){ua(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};k.goForwards=function(a,b){ua(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};
k.rotateOnce=function(a,b){this.C.play(void 0===a?0:a,b)};k.stopRotation=function(){this.C.stop()};k.getFrame=function(a){if(0!=this.c)return this.frames[a-1]};k.sa=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?K(d,this,{id:this.currentIndex}):K(d,this)}};
l.Object.defineProperties(U.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.c?this.a+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.j}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.c}}});l.Object.defineProperties(U,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ta}}});var va="images scaling has-navigation navigation-highlight navigation-thumbnails transition-duration exit-urls autoplay-duration autoplay-step-interval frame-width frame-height frame-snap-interval num-frames-to-display disable-gesture offset start-frame swipe-threshold-ratio swipe-committed-threshold-ratio pause-front-media resume-next-media".split(" "),V=function(){var a=U.call(this)||this;a.R=!1;a.b=null;a.S=null;a.M=!1;a.s=G(0);a.u=null;a.i=!1;a.g=null;a.ea=a.Aa.bind(a);a.ga=a.Ca.bind(a);a.ca=
a.ya.bind(a);a.da=a.za.bind(a);a.fa=a.Ba.bind(a);a.Y=a.va.bind(a);a.qa=a.Ga.bind(a);a.pa=a.Fa.bind(a);a.oa=a.Ea.bind(a);a.$=a.wa.bind(a);a.ha=a.xa.bind(a);a.ja=fa(a.Da.bind(a));a.L=K.bind(null,"firstinteraction",a);a.U=!1;a.G=[];a.B=a.sa.bind(a,a.G);a.V=0;a.W=0;a.J=0;a.na=0;a.ma=0;a.O=1;a.K=[];a.N=0;a.la=1;a.Ha=.7;a.H=0;a.I=!1;a.v=G(0);a.o=G(0);a.h=null;a.ba=-1;a.m=-1;a.Z=[];a.D=G(-1,-1);a.F=!1;return a};y(V,U);
V.prototype.connectedCallback=function(){if(!this.F){var a="y"==this.getAttribute("swipe-axis");this.f=G(a?0:1,a?1:0);if(this.M=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);a=document.createElement("gwd-gesture");a.className="gesture";this.u=a;this.F=!0}a=this.u;a.addEventListener("pointerover",this.ga,!1);a.addEventListener("pointerout",this.ea,!1);a.addEventListener("pointermove",this.ca,!1);a.addEventListener("track",this.qa,!1);a.addEventListener("trackend",
this.pa,!1);a.addEventListener("tap",this.oa,!1);this.addEventListener("frametap",this.$,!1);this.addEventListener("swipefinished",this.X,!1);this.addEventListener("transitionend",this.B,!1);this.addEventListener("webkitTransitionEnd",this.B,!1);this.gwdIsLoaded()||((a=ha(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());window.addEventListener("resize",this.ja,!1)};
V.prototype.disconnectedCallback=function(){window.removeEventListener("resize",this.ja,!1);var a=this.u;a.removeEventListener("pointerover",this.ga,!1);a.removeEventListener("pointerout",this.ea,!1);a.removeEventListener("pointermove",this.ca,!1);a.removeEventListener("track",this.qa,!1);a.removeEventListener("trackend",this.pa,!1);a.removeEventListener("tap",this.oa,!1);this.removeEventListener("frametap",this.$,!1);this.removeEventListener("swipefinished",this.X,!1);this.removeEventListener("transitionend",
this.B);this.removeEventListener("webkitTransitionEnd",this.B)};
V.prototype.attributeChangedCallback=function(a,b,c,d){if(this.F)switch(a){case "images":this.frames=oa(this.getAttribute("images"));wa(this);W(this);break;case "scaling":pa(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":xa(this);W(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":X(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":X(this);
W(this);break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":W(this);break;default:U.prototype.attributeChangedCallback.call(this,a,b,c,d)}else U.prototype.attributeChangedCallback.call(this,a,b,c,d)};
var X=function(a){var b=H(a,"num-frames-to-display",1),c=H(a,"frame-snap-interval",1),d=H(a,"transition-duration",600),e=H(a,"frame-width",-1),h=H(a,"frame-height",-1),g=I(a,"autoplay-duration",3E3),f=I(a,"autoplay-step-interval",0);a.D.x=e;a.D.y=h;-1!=B(a.D,a.f)?b=-1:0<b&&c>b&&(c=b);a.Z=ja(a);a.m=b;a.j=c;a.J=d;a.V=g;a.W=f},W=function(a){var b=G(a.clientWidth,a.clientHeight);a.h&&(b.y-=36,a.S.style.height=b.y+"px");var c=I(a,"swipe-threshold-ratio",.1),d=I(a,"swipe-committed-threshold-ratio",.5),
e=a.f,h=a.m,g=a.D,f=a.frames,t=parseInt(a.getAttribute("offset"),10);isNaN(t)&&(t=0);t=C(e,t);g=G(-1==g.x?b.x:g.x,-1==g.y?b.y:g.y);if(a.hasAttribute("offset")){a:{var r=g.x,p=g.y,D=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var w=a.getAttribute("clamp-frame-size-to-image");"true"==w?D=!0:"false"==w&&(D=!1)}if(D)if(w=a.hasAttribute("scaling")?a.getAttribute("scaling"):"contain",(D="contain"==w)||"none"==w)if(0==r||0==p)f={width:r,height:p};else{for(var L=w=-1,Ba=f.length,Q=0;Q<Ba;Q++){var u=
f[Q];if("img"!=u.tagName.toLowerCase()&&"gwd-image"!=u.tagName.toLowerCase()){f={width:r,height:p};break a}var x=u.assetWidth?u.assetWidth:u.naturalWidth,E=u.assetHeight?u.assetHeight:u.naturalHeight;0<x&&0<E&&(D?x/E<r/p?(u=x/E*p,x=p):(u=r,x=E/x*r):(u=x,x=E),w=Math.max(w,u),L=Math.max(L,x))}f={width:-1!=w?Math.min(r,w):r,height:-1!=L?Math.min(p,L):p}}else f={width:r,height:p};else f={width:r,height:p}}1==e.x?g.x=f.width:g.y=f.height}1<h&&(f=C(e,h-1),f=G(f.x*t.x,f.y*t.y),f=F(G((b.x-f.x)/h,(b.y-f.y)/
h),e),f.x&&(g.x=f.x),f.y&&(g.y=f.y));f=2<h?1+Math.ceil(h/2-1):1;r=parseInt(a.getAttribute("start-frame"),10);isNaN(r)&&(r=f);f=F(G(g.x+t.x,g.y+t.y),e);p=1+2*Math.floor((B(e,b)-B(e,g))/(2*B(e,f)));if(1>p||!isFinite(p))p=1;b=G((b.x-g.x)/2,(b.y-g.y)/2);0<h&&0==h%2&&(e=F(G(g.x+t.x,g.y+t.y),e),b.x-=.5*e.x,b.y-=.5*e.y,p+=1);e=a.hasAttribute("disable-gesture");a.o=g;a.v=b;a.O=p;a.H=B(f,a.f);a.la=r;a.i=e;a.na=B(a.o,a.f)*c;a.ma=B(a.o,a.f)*d;c=F(a.v,G(a.f.y,a.f.x));for(e=0;e<a.c;e++)d=a.frames[e].style,d.left=
c.x+"px",d.top=c.y+"px",d.width=a.o.x+"px",d.height=a.o.y+"px",c.x+=f.x,c.y+=f.y;a.s=G(0);a.b&&(Y(a,0,0,0),c=F(a.v,a.f),a.b.style.left=c.x+"px",a.b.style.top=c.y+"px");a.a=null;a.goToFrame(a.la,"none")};k=V.prototype;k.gwdIsLoaded=function(){return this.R};k.gwdLoad=function(){if(!this.R&&!this.b){if(this.M)var a=oa(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;wa(this)}};
k.goBackwards=function(a,b){return U.prototype.goBackwards.call(this,a,void 0===b?!1:b)};k.goForwards=function(a,b){return U.prototype.goForwards.call(this,a,void 0===b?!1:b)};
k.aa=function(a,b){var c=this.j;var d=this.c;var e=this.m;--a;a=a-a%c+Math.floor((c-1)/2);0>a?a=0:a>=d&&(a=d-1);1<e&&(c=a-Math.floor((e-1)/2),e=c+e-1,0>c&&e<d-1&&(a+=Math.min(-c,d-e-1)),e>=d&&0<c&&(a-=Math.min(e-d+1,c)));d=a;if(null!=this.a&&this.a!=d){if(this.ia)for(e=Array.prototype.slice.call(this.frames[this.a].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),a=0;a<e.length;a++)c=e[a],c.pause&&c.pause();if(this.ka)for(e=Array.prototype.slice.call(this.frames[d].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),
a=0;a<e.length;a++)c=e[a],c.play&&c.play()}e=this.a;this.a=d;d=C(this.f,-this.H*this.a);Y(this,"none"!=b?this.J:0,d.x,d.y);this.s=d;if(this.N)for(b=Math.floor((this.O-1)/2),d=0;d<this.O;d++)if(a=this.a-b+d,!(0>a||a>=this.c||this.K[a]||(this.K[a]=!0,--this.N))){this.G.push("allframesviewed");break}e!=this.a&&(ya(this,this.a+1),this.G.push("frameshown"),this.G.push("swipefinished"));this.U||this.B()};
var Y=function(a,b,c,d){a.U=0<b;N(a.b,"transition","transform "+b+"ms");N(a.b,"transform","translate3d("+c+"px,"+d+"px,0)")},wa=function(a){if(a.F){for(;a.firstChild;)a.removeChild(a.firstChild);a.h=null;a.b&&(a.b.removeEventListener("pageload",a.ha,!1),a.b.removeEventListener("mouseover",a.fa,!0),a.b.removeEventListener("mouseout",a.da,!0),a.b.removeEventListener("click",a.Y,!0));for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];N(e,"user-select","none");e.classList.add("frame");
c.appendChild(e)}ea(c,c.gwdLoad.bind(c));a.b=c;a.b.className="container";a.b.addEventListener("pageload",a.ha,!1);a.b.addEventListener("mouseover",a.fa,!0);a.b.addEventListener("mouseout",a.da,!0);a.b.addEventListener("click",a.Y,!0);pa(a.frames,a.getAttribute("scaling"));a.c=a.frames.length;b=a.ownerDocument.createElement("div");a.S=b;b.className="matte";b.appendChild(a.b);a.appendChild(a.S);a.appendChild(a.u)}};V.prototype.X=function(){N(this.b,"transition","transform 0ms")};
V.prototype.xa=function(a){a.target===this.b&&(this.R=!0,this.N=this.c,this.K=[],X(this),xa(this),W(this),K("allframesloaded",this),this.hasAttribute("autoplay")&&this.C.play(this.V,"forwards",this.W),K("ready",this))};V.prototype.Da=function(){X(this);W(this)};V.prototype.rotateOnce=function(a,b){this.C.play(a||this.J,b)};
var Aa=function(a,b){var c=a.c;if(c){var d=a.a;b=za(a,b);a.goToFrame(b+1);d!=b&&(0==b?K("reachleftend",a):b==c-1&&K("reachrightend",a))}},xa=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.h;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.h=a.ownerDocument.createElement("gwd-gallerynavigation"),a.h.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.h)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.h),a.h=null);a.h&&(ia(a,"navigation-highlight",a.h,"highlight"),
ia(a,"navigation-thumbnails",a.h,"use-thumbnails"))},za=function(a,b){var c=a.a;Math.abs(b)>a.na&&(c=0>b?c+a.j:c-a.j);0>c?c=0:c>=a.c&&(c=a.c-1);return c},ya=function(a,b){a.ba!=b&&(a.ba=b,K("frameactivated",a,{id:b||a.currentIndex}))};
V.prototype.Ga=function(a){if(!this.i&&(this.L&&(this.L(),this.L=null),!this.I))if(this.stopRotation(),a=B(G(a.dx,a.dy),this.f),ya(this,za(this,a)+1),Math.abs(a)>this.ma)Aa(this,a),this.I=!0;else{var b=a;if(0<a&&0===this.a||0>a&&this.a===this.c-1)b-=a*this.Ha;Y(this,0,this.s.x+this.f.x*b,this.s.y+this.f.y*b)}};V.prototype.Fa=function(a){this.i||(this.I?this.I=!1:Aa(this,B(G(a.dx,a.dy),this.f)))};
var Z=function(a,b){var c=a.getBoundingClientRect();b=G(b.clientX-c.left,b.clientY-c.top);c=a.f;var d=G(c.y,c.x);c=B(d,b);var e=B(d,a.v);d=B(d,a.o);if(c<e||c>e+d)return null;c=a.f;b=B(c,b)-B(c,a.s)-B(c,a.v);c=Math.floor(b/a.H);return 0>c||c>=a.c||b%a.H>B(a.f,a.o)?null:c};k=V.prototype;
k.Ea=function(a){if(!this.i){this.stopRotation();var b=this.u;var c=this.b;var d=a.clientX,e=a.clientY,h=b.style["pointer-events"];b.style["pointer-events"]="none";d=c.ownerDocument.elementFromPoint(d,e);b.style["pointer-events"]=h;if(b=d)if(c.contains&&1==d.nodeType)b=c==d||c.contains(d);else if("undefined"!=typeof c.compareDocumentPosition)b=c==d||!!(c.compareDocumentPosition(d)&16);else{for(b=d;b&&c!=b;)b=b.parentNode;b=b==c}c=b?d:null;(b=!c)||(b=a.clientX,h=a.clientY,d=!1,"gwd-taparea"===c.tagName.toLowerCase()&&
(d=c.ownerDocument.createEvent("Event"),d.initEvent("action",!0,!0),d.clientX=b,d.clientY=h,d=!c.dispatchEvent(d)),b=!d);b&&(a=Z(this,a),null!=a&&K("frametap",this,{element:this.frames[a],id:a+1}))}};
k.wa=function(a){if((a=a.detail&&a.detail.id)&&(a=this.Z[a-1])&&!K("frameexit",this,{url:a}).detail.handled){a instanceof S||a instanceof S||(a="object"==typeof a&&a.ua?a.ta():String(a),ka(na.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new S(a,ma));var b=a;a=z.open;if(b instanceof S&&b.constructor===S)b=b.T;else{var c=typeof b;la("expected object of type SafeUrl, got '"+b+"' of type "+("object"!=c?c:b?Array.isArray(b)?"array":c:"null"));b="type_error:SafeUrl"}a.call(z,
b,"")}};k.Aa=function(){this.i||null==this.g||(K("framemouseout",this,{element:this.frames[this.g],id:1+this.g}),this.g=null)};k.Ca=function(a){this.i||(a=Z(this,a),a!=this.g&&(null!=this.g&&K("framemouseout",this,{element:this.frames[this.g],id:1+this.g}),null!=a&&K("framemouseover",this,{element:this.frames[a],id:1+a}),this.g=a))};
k.ya=function(a){this.i||(a=Z(this,a),a!=this.g&&(null!=this.g&&K("framemouseout",this,{element:this.frames[this.g],id:1+this.g}),null!=a&&K("framemouseover",this,{element:this.frames[a],id:1+a}),this.g=a))};k.Ba=function(a){this.i&&a.target.classList.contains("frame")&&K("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};k.za=function(a){this.i&&a.target.classList.contains("frame")&&K("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
k.va=function(a){this.i&&a.target.classList.contains("frame")&&K("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
l.Object.defineProperties(V.prototype,{firstVisibleFrameIndex:{configurable:!0,enumerable:!0,get:function(){var a=0<this.m&&0<this.c&&null!=this.a?Math.max(1,this.a-Math.floor((this.m-1)/2)+1):void 0;return a}},lastVisibleFrameIndex:{configurable:!0,enumerable:!0,get:function(){var a=0<this.m&&0<this.c&&null!=this.a?Math.min(this.c,this.a-Math.floor((this.m-1)/2)+this.m):void 0;return a}}});l.Object.defineProperties(V,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return va}}});
customElements.define("gwd-swipegallery",V);}).call(this);
